@startuml RustDrop Class Diagram


' ─────────────────────────────────────────
' CLI
' ─────────────────────────────────────────
class CLI {
    + advertise
    + detect
    + sendfile
    + openToReception
}

' ─────────────────────────────────────────
' Main API — orchestration facade
' ─────────────────────────────────────────
class App {
    + advertise() -> Result<()>
    + detect_others() -> Result<()>
    + send_file(peer_id: PeerId, path: Path)
    + receive_file(request: TransferRequest)
}

' ─────────────────────────────────────────
' Peer Registry
' ─────────────────────────────────────────
class PeerRegistry {
    - peers
    + add(peer: Peer)
    + remove(peer_id: PeerId)
    + get(peer_id: PeerId)
}

class Peer {
    + id: PeerId
    + display_name: String
    + lan_ipaddr: String
    + identity ?
}

class DiscoveryComponent {
    + advertise()
    + stop_advertising()
    + scan(on_found: Fn(Peer))
    + stop_scan()
}


' ─────────────────────────────────────────
' Transfer Layer (TCP/TLS)
' ─────────────────────────────────────────
class TransferLayer {
    + negotiate_send(TransferMetaData) -> transfer
    + negotiate_receive() -> transfer
    + send() 
    + receive()
}

class TransferMetaData {
    + filename: String
    + filesize: u64
    + checksum: String
    + sender_name: String
    + tcp_addr: SocketAddr
}

' ─────────────────────────────────────────
' Relationships
' ─────────────────────────────────────────

CLI --> App : calls
App --> PeerRegistry : owns
App --> DiscoveryComponent : owns
App --> TransferLayer : owns
App --> Identity : owns ?

DiscoveryComponent --> PeerRegistry : add / remove peers
DiscoveryComponent --> Identity : reads identity\nfor advertisement ?


TransferLayer --> Identity : uses TLS cert\n+ verifies identity ?
TransferLayer ..> TransferMetaData : uses
TransferLayer --> PeerRegistry : transfers from/to

PeerRegistry "1" o-- "0..*" Peer : stores
Peer --> Identity : is identified as


note left of App
    main application abstraction,\n
    will allow to change CLI for GUI freely
end note

note left of TransferLayer
  TCP stream + TLS encryption ?
  checksum verification ?
end note

note bottom of PeerRegistry
  TTL expiry ofpeers
end note

note right of CLI
  send <peer> <file> (with autocomplete)
  accept / decline prompt
end note

note bottom of Identity
    will think about indentity and crypto later
end note

@enduml